version: "3.8"

services:
  web:
    container_name: web
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      API_BASE_URL: ${API_BASE_URL}
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

  bot:
    container_name: bot
    environment:
      BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
      API_BASE_URL: ${API_BASE_URL}
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    ports:
      - "8000:8000" 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
