import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Giverve Starterkit</title>
        <meta name="description" content="Generated by giverve-starterkit" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center justify-center bg-background">
        <p className="text-2xl text-foreground">
          {data ? data.greeting : "Loading tRPC query..."}
        </p>
      </main>
    </>
  );
}
