const {
  COOKIE_REFRESH_TOKEN_NAME = "_ry613q",
  COOKIE_ACCESS_TOKEN_NAME = "_721r1z",
  COOKIE_OAUTH_STATE_NAME = "_1r2y3k",
  COOKIE_JWT_NAME = "_1xy56kv",
} = process.env;

export {
  COOKIE_ACCESS_TOKEN_NAME,
  COOKIE_JWT_NAME,
  COOKIE_OAUTH_STATE_NAME,
  COOKIE_REFRESH_TOKEN_NAME,
};
